version: "3.4"
services:
  tools:
    build: 
      dockerfile: ./Dockerfile
      context: ./
    entrypoint: bash
    working_dir: /app
    volumes:
      - ./source:/app
      - /home/david/.ssh:/root/.ssh
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: eu-west-1